### ISSUE TITLE
"Bloomberg Style" seems to be broken on demo page

### ISSUE THREAD

**Issue by Qix-** [asvd/viewport#2] opened 2016-06-02 20:19 UTC
The demo page, at least on Chrome, seems to have a broken Bloomberg style (it never switches away from Astronomy).

**Comment by asvd** [comment] 2016-06-02 20:23
Can't reproduce (Chrome 48). Which Chrome version do you have? Is there any messages on console?

**Comment by Qix-** [comment] 2016-06-02 20:37
50.0.2661.102 (64-bit) on OS X. No errors in the console.

![Demo](http://g.recordit.co/SSh6sa3N9k.gif)

**Comment by asvd** [comment] 2016-11-16 10:48
ok, reproduced

**Comment by asvd** [comment] 2016-11-20 22:12
fixed in v0.0.5

**Closed as completed by asvd** 2016-11-20 22:12 UTC
